### ISSUE TITLE
http: command not found

### ISSUE THREAD

**Issue by robmarkcole** [aws-samples/amazon-sagemaker-endpoint-deployment-of-fastai-model-with-torchserve#7]
The example request using http fails on sagemaker notebook since `http: command not found`

Propose instead 
```
curl -X POST http://127.0.0.1:8080/predictions/fastunet -T sample/street_view_of_a_small_neighborhood.png
```

**Comment by sunbc0120** [comment]
Consider install via:

https://httpie.io/

or use `curl` as you suggested.
