### ISSUE TITLE
Fastai2 model deployment

### ISSUE THREAD

**Issue by m-ali-awan** [aws-samples/amazon-sagemaker-endpoint-deployment-of-fastai-model-with-torchserve#8]
I donot know, why is it not finding the model??

FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'
--

Thanks, for any help

**Comment by sunbc0120** [comment]
Please provide more detail and steps to reproduce the error.

**Comment by sunbc0120** [comment]
Also consider the suggestion listed here: https://github.com/aws-samples/amazon-sagemaker-endpoint-deployment-of-fastai-model-with-torchserve/issues/6#issuecomment-846452627

**Comment by sunbc0120** [comment]
no following up.
